### ISSUE TITLE
使用xuri/excelize/v2 bee run启动不了

### ISSUE THREAD

**Issue by actoy** [beego/beedoc#967]
![image](https://user-images.githubusercontent.com/5004886/232014867-082532aa-0e6e-4050-8bcc-48bf02345213.png)

使用xuri/excelize/v2 bee run启动不了，会卡住，无响应

**Comment by flycash** [comment]
你这看上去不是启动不了，是你在拉 excelize 后面的依赖出了问题，卡住了。输出的日志是说，你已经拉到了 xuri/execlize/v2 依赖。然后下一个步骤卡住了。如果 bee run 有问题，那么应该至少输出 bee 已经启动的信息。 从 Windows 版邮件发送 发件人: actoy发送时间: 2023年4月14日 18:03收件人: beego/beedoc抄送: Subscribed主题: [beego/beedoc] 使用xuri/excelize/v2 bee run启动不了 (Issue #967) 使用xuri/excelize/v2 bee run启动不了—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by actoy** [comment]
> 
然后下一个步骤卡住了 具体是指什么报错，这个可以看到么。

**Comment by flycash** [comment]
目前我倒是看不出来，你看看在你的 gosum 里面下一个依赖是啥。 不过你可以考虑不管这种问题，开个 VPN 应该就可以了。 从 Windows 版邮件发送 发件人: actoy发送时间: 2023年4月14日 18:45收件人: beego/beedoc抄送: Ming Deng; Comment主题: Re: [beego/beedoc] 使用xuri/excelize/v2 bee run启动不了 (Issue #967) 然后下一个步骤卡住了 具体是指什么报错，这个可以看到么。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by actoy** [comment]
> 目前我倒是看不出来，你看看在你的 gosum 里面下一个依赖是啥。 不过你可以考虑不管这种问题，开个 VPN 应该就可以了。 从 Windows 版邮件发送 发件人: actoy发送时间: 2023年4月14日 18:45收件人: beego/beedoc抄送: Ming Deng; Comment主题: Re: [beego/beedoc] 使用xuri/excelize/v2 bee run启动不了 (Issue #967) 然后下一个步骤卡住了 具体是指什么报错，这个可以看到么。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

服务器在香港，这种不需要VPN吧

**Comment by flycash** [comment]
那就应该不是这个问题了。目前我只能看出来它卡住了，但是不知道你这里为啥卡住了。说实在的，你可以直接用 go run 命令试试的 从 Windows 版邮件发送 发件人: actoy发送时间: 2023年4月14日 18:51收件人: beego/beedoc抄送: Ming Deng; Comment主题: Re: [beego/beedoc] 使用xuri/excelize/v2 bee run启动不了 (Issue #967) 目前我倒是看不出来，你看看在你的 gosum 里面下一个依赖是啥。 不过你可以考虑不管这种问题，开个 VPN 应该就可以了。 从 Windows 版邮件发送 发件人: actoy发送时间: 2023年4月14日 18:45收件人: beego/beedoc抄送: Ming Deng; Comment主题: Re: [beego/beedoc] 使用xuri/excelize/v2 bee run启动不了 (Issue #967) 然后下一个步骤卡住了 具体是指什么报错，这个可以看到么。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> 服务器在香港，这种不需要VPN吧—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by actoy** [comment]
> 那就应该不是这个问题了。目前我只能看出来它卡住了，但是不知道你这里为啥卡住了。说实在的，你可以直接用 go run 命令试试的 从 Windows 版邮件发送 发件人: actoy发送时间: 2023年4月14日 18:51收件人: beego/beedoc抄送: Ming Deng; Comment主题: Re: [beego/beedoc] 使用xuri/excelize/v2 bee run启动不了 (Issue #967) 目前我倒是看不出来，你看看在你的 gosum 里面下一个依赖是啥。 不过你可以考虑不管这种问题，开个 VPN 应该就可以了。 从 Windows 版邮件发送 发件人: actoy发送时间: 2023年4月14日 18:45收件人: beego/beedoc抄送: Ming Deng; Comment主题: Re: [beego/beedoc] 使用xuri/excelize/v2 bee run启动不了 (Issue #967) 然后下一个步骤卡住了 具体是指什么报错，这个可以看到么。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***> 服务器在香港，这种不需要VPN吧—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

go run 一次后，问题解决了 感谢感谢
